spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 111
            clientSecret: 111
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 465
    username: gusghk115@gmail.com
    password: qaditftpldbkhoyu
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com